### ISSUE TITLE
sudo-write-quit?

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-sudo-write#3]
Tried to add this kind of command myself via

```
define-command sudo-write-quit %{
    sudo-write
    quit
}
```

But Kakoune exits immediately. Same happens if called interactively `:sudo-write; quit`

**Comment by occivink** [comment]
Yes, you're encountering this issue https://github.com/mawww/kakoune/issues/2216
I'm not sure if there's a good solution to it, short of providing a `sudo-write-quit` command in the plugin itself.

**Comment by andreyorst** [comment]
Hm, I see. I have an idea

**Comment by occivink** [comment]
what would it be? 
For the record, I still think that the current kakoune behavior is not great, specifically because it makes commands like this one difficult to extend.

**Comment by andreyorst** [comment]
> what would it be?
> For the record, I still think that the current kakoune behavior is not great, specifically because it makes commands like this one difficult to extend.

Yeah, I agree. My idea was to create lock file and wait until it was removed and issue `quit`, but I've not succeeded yet
